const ReportReasons = Object.freeze([
  { itemID: "0", description: "頭像/資料不實" },
  { itemID: "1", description: "惡意話語/攻擊" },
  { itemID: "2", description: "惡意騷擾" },
  { itemID: "3", description: "色情低俗" },
  { itemID: "4", description: "疑似詐騙/釣魚" },
  { itemID: "5", description: "廣告/銷售" },
  { itemID: "6", description: "未成年" },
  { itemID: "7", description: "其他原因" },
]);

const Interesteds = Object.freeze([
  { itemID: "0", description: "聽音樂" },
  { itemID: "1", description: "玩音樂" },
  { itemID: "2", description: "運動" },
  { itemID: "3", description: "健身" },
  { itemID: "4", description: "吃美食" },
  { itemID: "5", description: "烹飪" },
  { itemID: "6", description: "電影" },
  { itemID: "7", description: "遊戲" },
  { itemID: "8", description: "動漫" },
  { itemID: "9", description: "閱讀" },
  { itemID: "10", description: "旅遊" },
  { itemID: "11", description: "喝酒" },
  { itemID: "12", description: "刺青" },
  { itemID: "13", description: "釣魚" },
  { itemID: "14", description: "攝影" },
  { itemID: "15", description: "寫作" },
  { itemID: "16", description: "跳舞" },
  { itemID: "17", description: "夾娃娃" },
  { itemID: "18", description: "模型" },
  { itemID: "19", description: "發呆" },
  { itemID: "20", description: "睡覺" },
  { itemID: "21", description: "騎車" },
  { itemID: "22", description: "釣魚" },
  { itemID: "23", description: "散步" },
  { itemID: "24", description: "美妝" },
  { itemID: "25", description: "時尚" },
  { itemID: "26", description: "追星" },
  { itemID: "27", description: "夜生活" },
  { itemID: "28", description: "追劇" },
]);

const Traits = Object.freeze([
  { itemID: "0", description: "愛講幹話" },
  { itemID: "1", description: "撿到槍" },
  { itemID: "2", description: "情緒穩定" },
  { itemID: "3", description: "一枚小可愛" },
  { itemID: "4", description: "邏輯派" },
  { itemID: "5", description: "感性派" },
  { itemID: "6", description: "腦洞很大" },
  { itemID: "7", description: "內向" },
  { itemID: "8", description: "外向" },
  { itemID: "9", description: "隨性自由" },
  { itemID: "10", description: "表裡如一" },
  { itemID: "11", description: "行動派" },
  { itemID: "12", description: "善於傾聽" },
  { itemID: "13", description: "誠實" },
  { itemID: "14", description: "愛聊天" },
  { itemID: "15", description: "享受孤獨" },
  { itemID: "16", description: "吃軟不吃硬" },
  { itemID: "17", description: "愛已讀亂回" },
  { itemID: "18", description: "不按牌理出牌" },
  { itemID: "19", description: "幽默" },
  { itemID: "20", description: "可鹽可甜" },
  { itemID: "21", description: "常被說直男" },
]);

const FriendMotives = Object.freeze([
  { itemID: "0", description: "想拓展朋友圈" },
  { itemID: "1", description: "想交志同道合的朋友" },
  { itemID: "2", description: "想享受曖昧" },
  { itemID: "3", description: "想脫離單身" },
  { itemID: "4", description: "好奇玩看看" },
  { itemID: "5", description: "排遣無聊" },
  { itemID: "6", description: "抒發情緒" },
]);

const Values = Object.freeze([
  { itemID: "0", description: "另一半跟朋友都重要" },
  { itemID: "1", description: "一個人也不錯" },
  { itemID: "2", description: "相信一見鍾情" },
  { itemID: "3", description: "相信日久生情" },
  { itemID: "4", description: "不婚主義" },
  { itemID: "5", description: "工作大於戀愛" },
  { itemID: "6", description: "拒絕公主王子病" },
  { itemID: "7", description: "拒絕媽寶爸寶" },
  { itemID: "8", description: "有訊息就會回" },
  { itemID: "9", description: "戀愛放第一" },
  { itemID: "10", description: "浪漫主義" },
  { itemID: "11", description: "女權主義" },
  { itemID: "12", description: "男權主義" },
  { itemID: "13", description: "平權主義" },
  { itemID: "14", description: "拒絕已讀不回" },
  { itemID: "15", description: "拒絕已讀亂回" },
  { itemID: "16", description: "需有同理心" },
  { itemID: "17", description: "承諾必須做到" },
  { itemID: "18", description: "AA制" },
]);

module.exports = {
  ReportReasons,
  Interesteds,
  Traits,
  FriendMotives,
  Values,
};
